### ISSUE TITLE
How to change background color of the main page?

### ISSUE THREAD

**Issue by sarptekbas** [hadenpf/bankboga#13]
Hello guys I was fiddling with this and found the main.pcss file and there was the background color section of the main landing page. I changes it and run the docker container again but it didn't work. What should I do to change the bacground color?

**Comment by sarptekbas** [comment]
Solved it by rebuilding the Docker container.

**Comment by hadenpf** [comment]
Hey @sarptekbas!

Thanks for your interest in the project. I haven't maintained it for a long time now but glad to know that people are still getting some sort of value from it. Let me know if you run into any other issues — I plan to eventually refactor the code & improve it once I have the time.

~ Haden
