### ISSUE TITLE
Logging in 

### ISSUE THREAD

**Issue by GhostGuy9** [hadenpf/bankboga#2]
How do i log in? Random or fixed?

edit: Got it working, something about the length part of the pass word broke it.

**Comment by GhostGuy9** [comment]
Now i need the password, got the user

**Comment by tarjayylmao69** [comment]
What is the username and password?

**Comment by GhostGuy9** [comment]
- [x] @tarjayylmao69 you can find it in the userauth.js file.

**Comment by faille13** [comment]
Can you please explain to me to figureout the user/password.... or creating my own... thank you

**Comment by faille13** [comment]
@GhostGuy9

**Comment by GhostGuy9** [comment]
> @GhostGuy9

Like i said to @tarjayylmao69, you can find the code for the User/Pass in the apps\userauth.js file.

The User can be anything from j.doe#8127 or g.guy#2983 doesnt matter.
The password is set up to need 'asdfasdf' but can be modded to be also random or static.

the code is to show how it works. its a direct copy and hasn't been changed

`function validateUsername(username) {
    if (username === undefined)
        return false

    const match = username.match(/^([A-Za-z0-9._ ]+)#\d{4}$/)

    if (match)
        return match[1]

    return false
}`

`function validatePassword(password) {
    if (password === undefined)
        return false

    if (password.length >= 16
        && password.includes('asdfasdf'))
        return true

    return false
}`

**Comment by faille13** [comment]
THANK YOU SO MUCH
